// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AudioUIClient is the client API for AudioUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioUIClient interface {
	// ListEngineSpecs returns a list of Audio Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (AudioUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type audioUIClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioUIClient(cc grpc.ClientConnInterface) AudioUIClient {
	return &audioUIClient{cc}
}

func (c *audioUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (AudioUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioUI_ServiceDesc.Streams[0], "/v1.AudioUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &audioUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AudioUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type audioUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *audioUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *audioUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.AudioUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioUIServer is the server API for AudioUI service.
// All implementations must embed UnimplementedAudioUIServer
// for forward compatibility
type AudioUIServer interface {
	// ListEngineSpecs returns a list of Audio Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, AudioUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedAudioUIServer()
}

// UnimplementedAudioUIServer must be embedded to have forward compatible implementations.
type UnimplementedAudioUIServer struct {
}

func (UnimplementedAudioUIServer) ListEngineSpecs(*ListEngineSpecsRequest, AudioUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedAudioUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedAudioUIServer) mustEmbedUnimplementedAudioUIServer() {}

// UnsafeAudioUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioUIServer will
// result in compilation errors.
type UnsafeAudioUIServer interface {
	mustEmbedUnimplementedAudioUIServer()
}

func RegisterAudioUIServer(s grpc.ServiceRegistrar, srv AudioUIServer) {
	s.RegisterService(&AudioUI_ServiceDesc, srv)
}

func _AudioUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioUIServer).ListEngineSpecs(m, &audioUIListEngineSpecsServer{stream})
}

type AudioUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type audioUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *audioUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AudioUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AudioUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioUI_ServiceDesc is the grpc.ServiceDesc for AudioUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AudioUI",
	HandlerType: (*AudioUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _AudioUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _AudioUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "audio-ui.proto",
}
